version: '3.3'

services:

    # node:
    #     build:
    #         context: ./node
    #         args:
    #             - NODE_VERSION=latest
    #             - PROJECT_PATH=/opt/app/
    #             - NODE_ENV=production
    #             - YARN=false
    #     volumes:
    #         - ../:/opt/app
    #     entrypoint: run-nodock "node index.js"
    #     tty: true

    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_DATABASE=birdbase
                - MYSQL_USER=birdbase
                - MYSQL_PASSWORD=password
                - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./data/mysql/:/var/lib/mysql
        ports:
            - "3306:3306"
        expose:
            - "3306"